# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1381/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1381/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/moude/CLionProjects/pgMark

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/moude/CLionProjects/pgMark

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1381/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1381/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/moude/CLionProjects/pgMark/CMakeFiles /mnt/c/Users/moude/CLionProjects/pgMark//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/moude/CLionProjects/pgMark/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pugixml

# Build rule for target.
pugixml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pugixml
.PHONY : pugixml

# fast build rule for target.
pugixml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pugixml.dir/build.make CMakeFiles/pugixml.dir/build
.PHONY : pugixml/fast

#=============================================================================
# Target rules for targets named regex

# Build rule for target.
regex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 regex
.PHONY : regex

# fast build rule for target.
regex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/build
.PHONY : regex/fast

#=============================================================================
# Target rules for targets named pgMark

# Build rule for target.
pgMark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pgMark
.PHONY : pgMark

# fast build rule for target.
pgMark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/build
.PHONY : pgMark/fast

src/attribute.o: src/attribute.cpp.o
.PHONY : src/attribute.o

# target to build an object file
src/attribute.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/attribute.cpp.o
.PHONY : src/attribute.cpp.o

src/attribute.i: src/attribute.cpp.i
.PHONY : src/attribute.i

# target to preprocess a source file
src/attribute.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/attribute.cpp.i
.PHONY : src/attribute.cpp.i

src/attribute.s: src/attribute.cpp.s
.PHONY : src/attribute.s

# target to generate assembly for a file
src/attribute.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/attribute.cpp.s
.PHONY : src/attribute.cpp.s

src/configuration.o: src/configuration.cpp.o
.PHONY : src/configuration.o

# target to build an object file
src/configuration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/configuration.cpp.o
.PHONY : src/configuration.cpp.o

src/configuration.i: src/configuration.cpp.i
.PHONY : src/configuration.i

# target to preprocess a source file
src/configuration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/configuration.cpp.i
.PHONY : src/configuration.cpp.i

src/configuration.s: src/configuration.cpp.s
.PHONY : src/configuration.s

# target to generate assembly for a file
src/configuration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/configuration.cpp.s
.PHONY : src/configuration.cpp.s

src/graph_generator.o: src/graph_generator.cpp.o
.PHONY : src/graph_generator.o

# target to build an object file
src/graph_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/graph_generator.cpp.o
.PHONY : src/graph_generator.cpp.o

src/graph_generator.i: src/graph_generator.cpp.i
.PHONY : src/graph_generator.i

# target to preprocess a source file
src/graph_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/graph_generator.cpp.i
.PHONY : src/graph_generator.cpp.i

src/graph_generator.s: src/graph_generator.cpp.s
.PHONY : src/graph_generator.s

# target to generate assembly for a file
src/graph_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/graph_generator.cpp.s
.PHONY : src/graph_generator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/node_attribute_generator.o: src/node_attribute_generator.cpp.o
.PHONY : src/node_attribute_generator.o

# target to build an object file
src/node_attribute_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/node_attribute_generator.cpp.o
.PHONY : src/node_attribute_generator.cpp.o

src/node_attribute_generator.i: src/node_attribute_generator.cpp.i
.PHONY : src/node_attribute_generator.i

# target to preprocess a source file
src/node_attribute_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/node_attribute_generator.cpp.i
.PHONY : src/node_attribute_generator.cpp.i

src/node_attribute_generator.s: src/node_attribute_generator.cpp.s
.PHONY : src/node_attribute_generator.s

# target to generate assembly for a file
src/node_attribute_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/node_attribute_generator.cpp.s
.PHONY : src/node_attribute_generator.cpp.s

src/pugixml.o: src/pugixml.cpp.o
.PHONY : src/pugixml.o

# target to build an object file
src/pugixml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pugixml.dir/build.make CMakeFiles/pugixml.dir/src/pugixml.cpp.o
.PHONY : src/pugixml.cpp.o

src/pugixml.i: src/pugixml.cpp.i
.PHONY : src/pugixml.i

# target to preprocess a source file
src/pugixml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pugixml.dir/build.make CMakeFiles/pugixml.dir/src/pugixml.cpp.i
.PHONY : src/pugixml.cpp.i

src/pugixml.s: src/pugixml.cpp.s
.PHONY : src/pugixml.s

# target to generate assembly for a file
src/pugixml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pugixml.dir/build.make CMakeFiles/pugixml.dir/src/pugixml.cpp.s
.PHONY : src/pugixml.cpp.s

src/random_distribution.o: src/random_distribution.cpp.o
.PHONY : src/random_distribution.o

# target to build an object file
src/random_distribution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/random_distribution.cpp.o
.PHONY : src/random_distribution.cpp.o

src/random_distribution.i: src/random_distribution.cpp.i
.PHONY : src/random_distribution.i

# target to preprocess a source file
src/random_distribution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/random_distribution.cpp.i
.PHONY : src/random_distribution.cpp.i

src/random_distribution.s: src/random_distribution.cpp.s
.PHONY : src/random_distribution.s

# target to generate assembly for a file
src/random_distribution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/random_distribution.cpp.s
.PHONY : src/random_distribution.cpp.s

src/random_string_generator.o: src/random_string_generator.cpp.o
.PHONY : src/random_string_generator.o

# target to build an object file
src/random_string_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/random_string_generator.cpp.o
.PHONY : src/random_string_generator.cpp.o

src/random_string_generator.i: src/random_string_generator.cpp.i
.PHONY : src/random_string_generator.i

# target to preprocess a source file
src/random_string_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/random_string_generator.cpp.i
.PHONY : src/random_string_generator.cpp.i

src/random_string_generator.s: src/random_string_generator.cpp.s
.PHONY : src/random_string_generator.s

# target to generate assembly for a file
src/random_string_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/random_string_generator.cpp.s
.PHONY : src/random_string_generator.cpp.s

src/regex_parser/branch.o: src/regex_parser/branch.cpp.o
.PHONY : src/regex_parser/branch.o

# target to build an object file
src/regex_parser/branch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/branch.cpp.o
.PHONY : src/regex_parser/branch.cpp.o

src/regex_parser/branch.i: src/regex_parser/branch.cpp.i
.PHONY : src/regex_parser/branch.i

# target to preprocess a source file
src/regex_parser/branch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/branch.cpp.i
.PHONY : src/regex_parser/branch.cpp.i

src/regex_parser/branch.s: src/regex_parser/branch.cpp.s
.PHONY : src/regex_parser/branch.s

# target to generate assembly for a file
src/regex_parser/branch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/branch.cpp.s
.PHONY : src/regex_parser/branch.cpp.s

src/regex_parser/character_sets.o: src/regex_parser/character_sets.cpp.o
.PHONY : src/regex_parser/character_sets.o

# target to build an object file
src/regex_parser/character_sets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/character_sets.cpp.o
.PHONY : src/regex_parser/character_sets.cpp.o

src/regex_parser/character_sets.i: src/regex_parser/character_sets.cpp.i
.PHONY : src/regex_parser/character_sets.i

# target to preprocess a source file
src/regex_parser/character_sets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/character_sets.cpp.i
.PHONY : src/regex_parser/character_sets.cpp.i

src/regex_parser/character_sets.s: src/regex_parser/character_sets.cpp.s
.PHONY : src/regex_parser/character_sets.s

# target to generate assembly for a file
src/regex_parser/character_sets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/character_sets.cpp.s
.PHONY : src/regex_parser/character_sets.cpp.s

src/regex_parser/group_ref.o: src/regex_parser/group_ref.cpp.o
.PHONY : src/regex_parser/group_ref.o

# target to build an object file
src/regex_parser/group_ref.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/group_ref.cpp.o
.PHONY : src/regex_parser/group_ref.cpp.o

src/regex_parser/group_ref.i: src/regex_parser/group_ref.cpp.i
.PHONY : src/regex_parser/group_ref.i

# target to preprocess a source file
src/regex_parser/group_ref.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/group_ref.cpp.i
.PHONY : src/regex_parser/group_ref.cpp.i

src/regex_parser/group_ref.s: src/regex_parser/group_ref.cpp.s
.PHONY : src/regex_parser/group_ref.s

# target to generate assembly for a file
src/regex_parser/group_ref.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/group_ref.cpp.s
.PHONY : src/regex_parser/group_ref.cpp.s

src/regex_parser/group_ref_exists.o: src/regex_parser/group_ref_exists.cpp.o
.PHONY : src/regex_parser/group_ref_exists.o

# target to build an object file
src/regex_parser/group_ref_exists.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/group_ref_exists.cpp.o
.PHONY : src/regex_parser/group_ref_exists.cpp.o

src/regex_parser/group_ref_exists.i: src/regex_parser/group_ref_exists.cpp.i
.PHONY : src/regex_parser/group_ref_exists.i

# target to preprocess a source file
src/regex_parser/group_ref_exists.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/group_ref_exists.cpp.i
.PHONY : src/regex_parser/group_ref_exists.cpp.i

src/regex_parser/group_ref_exists.s: src/regex_parser/group_ref_exists.cpp.s
.PHONY : src/regex_parser/group_ref_exists.s

# target to generate assembly for a file
src/regex_parser/group_ref_exists.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/group_ref_exists.cpp.s
.PHONY : src/regex_parser/group_ref_exists.cpp.s

src/regex_parser/in.o: src/regex_parser/in.cpp.o
.PHONY : src/regex_parser/in.o

# target to build an object file
src/regex_parser/in.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/in.cpp.o
.PHONY : src/regex_parser/in.cpp.o

src/regex_parser/in.i: src/regex_parser/in.cpp.i
.PHONY : src/regex_parser/in.i

# target to preprocess a source file
src/regex_parser/in.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/in.cpp.i
.PHONY : src/regex_parser/in.cpp.i

src/regex_parser/in.s: src/regex_parser/in.cpp.s
.PHONY : src/regex_parser/in.s

# target to generate assembly for a file
src/regex_parser/in.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/in.cpp.s
.PHONY : src/regex_parser/in.cpp.s

src/regex_parser/max_repeat.o: src/regex_parser/max_repeat.cpp.o
.PHONY : src/regex_parser/max_repeat.o

# target to build an object file
src/regex_parser/max_repeat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/max_repeat.cpp.o
.PHONY : src/regex_parser/max_repeat.cpp.o

src/regex_parser/max_repeat.i: src/regex_parser/max_repeat.cpp.i
.PHONY : src/regex_parser/max_repeat.i

# target to preprocess a source file
src/regex_parser/max_repeat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/max_repeat.cpp.i
.PHONY : src/regex_parser/max_repeat.cpp.i

src/regex_parser/max_repeat.s: src/regex_parser/max_repeat.cpp.s
.PHONY : src/regex_parser/max_repeat.s

# target to generate assembly for a file
src/regex_parser/max_repeat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/max_repeat.cpp.s
.PHONY : src/regex_parser/max_repeat.cpp.s

src/regex_parser/min_repeat.o: src/regex_parser/min_repeat.cpp.o
.PHONY : src/regex_parser/min_repeat.o

# target to build an object file
src/regex_parser/min_repeat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/min_repeat.cpp.o
.PHONY : src/regex_parser/min_repeat.cpp.o

src/regex_parser/min_repeat.i: src/regex_parser/min_repeat.cpp.i
.PHONY : src/regex_parser/min_repeat.i

# target to preprocess a source file
src/regex_parser/min_repeat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/min_repeat.cpp.i
.PHONY : src/regex_parser/min_repeat.cpp.i

src/regex_parser/min_repeat.s: src/regex_parser/min_repeat.cpp.s
.PHONY : src/regex_parser/min_repeat.s

# target to generate assembly for a file
src/regex_parser/min_repeat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/min_repeat.cpp.s
.PHONY : src/regex_parser/min_repeat.cpp.s

src/regex_parser/opcode.o: src/regex_parser/opcode.cpp.o
.PHONY : src/regex_parser/opcode.o

# target to build an object file
src/regex_parser/opcode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/opcode.cpp.o
.PHONY : src/regex_parser/opcode.cpp.o

src/regex_parser/opcode.i: src/regex_parser/opcode.cpp.i
.PHONY : src/regex_parser/opcode.i

# target to preprocess a source file
src/regex_parser/opcode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/opcode.cpp.i
.PHONY : src/regex_parser/opcode.cpp.i

src/regex_parser/opcode.s: src/regex_parser/opcode.cpp.s
.PHONY : src/regex_parser/opcode.s

# target to generate assembly for a file
src/regex_parser/opcode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/opcode.cpp.s
.PHONY : src/regex_parser/opcode.cpp.s

src/regex_parser/sre_parse.o: src/regex_parser/sre_parse.cpp.o
.PHONY : src/regex_parser/sre_parse.o

# target to build an object file
src/regex_parser/sre_parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/sre_parse.cpp.o
.PHONY : src/regex_parser/sre_parse.cpp.o

src/regex_parser/sre_parse.i: src/regex_parser/sre_parse.cpp.i
.PHONY : src/regex_parser/sre_parse.i

# target to preprocess a source file
src/regex_parser/sre_parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/sre_parse.cpp.i
.PHONY : src/regex_parser/sre_parse.cpp.i

src/regex_parser/sre_parse.s: src/regex_parser/sre_parse.cpp.s
.PHONY : src/regex_parser/sre_parse.s

# target to generate assembly for a file
src/regex_parser/sre_parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/sre_parse.cpp.s
.PHONY : src/regex_parser/sre_parse.cpp.s

src/regex_parser/state.o: src/regex_parser/state.cpp.o
.PHONY : src/regex_parser/state.o

# target to build an object file
src/regex_parser/state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/state.cpp.o
.PHONY : src/regex_parser/state.cpp.o

src/regex_parser/state.i: src/regex_parser/state.cpp.i
.PHONY : src/regex_parser/state.i

# target to preprocess a source file
src/regex_parser/state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/state.cpp.i
.PHONY : src/regex_parser/state.cpp.i

src/regex_parser/state.s: src/regex_parser/state.cpp.s
.PHONY : src/regex_parser/state.s

# target to generate assembly for a file
src/regex_parser/state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/state.cpp.s
.PHONY : src/regex_parser/state.cpp.s

src/regex_parser/subpattern.o: src/regex_parser/subpattern.cpp.o
.PHONY : src/regex_parser/subpattern.o

# target to build an object file
src/regex_parser/subpattern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/subpattern.cpp.o
.PHONY : src/regex_parser/subpattern.cpp.o

src/regex_parser/subpattern.i: src/regex_parser/subpattern.cpp.i
.PHONY : src/regex_parser/subpattern.i

# target to preprocess a source file
src/regex_parser/subpattern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/subpattern.cpp.i
.PHONY : src/regex_parser/subpattern.cpp.i

src/regex_parser/subpattern.s: src/regex_parser/subpattern.cpp.s
.PHONY : src/regex_parser/subpattern.s

# target to generate assembly for a file
src/regex_parser/subpattern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/subpattern.cpp.s
.PHONY : src/regex_parser/subpattern.cpp.s

src/regex_parser/subpattern_opcode.o: src/regex_parser/subpattern_opcode.cpp.o
.PHONY : src/regex_parser/subpattern_opcode.o

# target to build an object file
src/regex_parser/subpattern_opcode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/subpattern_opcode.cpp.o
.PHONY : src/regex_parser/subpattern_opcode.cpp.o

src/regex_parser/subpattern_opcode.i: src/regex_parser/subpattern_opcode.cpp.i
.PHONY : src/regex_parser/subpattern_opcode.i

# target to preprocess a source file
src/regex_parser/subpattern_opcode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/subpattern_opcode.cpp.i
.PHONY : src/regex_parser/subpattern_opcode.cpp.i

src/regex_parser/subpattern_opcode.s: src/regex_parser/subpattern_opcode.cpp.s
.PHONY : src/regex_parser/subpattern_opcode.s

# target to generate assembly for a file
src/regex_parser/subpattern_opcode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/subpattern_opcode.cpp.s
.PHONY : src/regex_parser/subpattern_opcode.cpp.s

src/regex_parser/tokenizer.o: src/regex_parser/tokenizer.cpp.o
.PHONY : src/regex_parser/tokenizer.o

# target to build an object file
src/regex_parser/tokenizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/tokenizer.cpp.o
.PHONY : src/regex_parser/tokenizer.cpp.o

src/regex_parser/tokenizer.i: src/regex_parser/tokenizer.cpp.i
.PHONY : src/regex_parser/tokenizer.i

# target to preprocess a source file
src/regex_parser/tokenizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/tokenizer.cpp.i
.PHONY : src/regex_parser/tokenizer.cpp.i

src/regex_parser/tokenizer.s: src/regex_parser/tokenizer.cpp.s
.PHONY : src/regex_parser/tokenizer.s

# target to generate assembly for a file
src/regex_parser/tokenizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/regex.dir/build.make CMakeFiles/regex.dir/src/regex_parser/tokenizer.cpp.s
.PHONY : src/regex_parser/tokenizer.cpp.s

src/schema.o: src/schema.cpp.o
.PHONY : src/schema.o

# target to build an object file
src/schema.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/schema.cpp.o
.PHONY : src/schema.cpp.o

src/schema.i: src/schema.cpp.i
.PHONY : src/schema.i

# target to preprocess a source file
src/schema.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/schema.cpp.i
.PHONY : src/schema.cpp.i

src/schema.s: src/schema.cpp.s
.PHONY : src/schema.s

# target to generate assembly for a file
src/schema.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pgMark.dir/build.make CMakeFiles/pgMark.dir/src/schema.cpp.s
.PHONY : src/schema.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pgMark"
	@echo "... pugixml"
	@echo "... regex"
	@echo "... src/attribute.o"
	@echo "... src/attribute.i"
	@echo "... src/attribute.s"
	@echo "... src/configuration.o"
	@echo "... src/configuration.i"
	@echo "... src/configuration.s"
	@echo "... src/graph_generator.o"
	@echo "... src/graph_generator.i"
	@echo "... src/graph_generator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/node_attribute_generator.o"
	@echo "... src/node_attribute_generator.i"
	@echo "... src/node_attribute_generator.s"
	@echo "... src/pugixml.o"
	@echo "... src/pugixml.i"
	@echo "... src/pugixml.s"
	@echo "... src/random_distribution.o"
	@echo "... src/random_distribution.i"
	@echo "... src/random_distribution.s"
	@echo "... src/random_string_generator.o"
	@echo "... src/random_string_generator.i"
	@echo "... src/random_string_generator.s"
	@echo "... src/regex_parser/branch.o"
	@echo "... src/regex_parser/branch.i"
	@echo "... src/regex_parser/branch.s"
	@echo "... src/regex_parser/character_sets.o"
	@echo "... src/regex_parser/character_sets.i"
	@echo "... src/regex_parser/character_sets.s"
	@echo "... src/regex_parser/group_ref.o"
	@echo "... src/regex_parser/group_ref.i"
	@echo "... src/regex_parser/group_ref.s"
	@echo "... src/regex_parser/group_ref_exists.o"
	@echo "... src/regex_parser/group_ref_exists.i"
	@echo "... src/regex_parser/group_ref_exists.s"
	@echo "... src/regex_parser/in.o"
	@echo "... src/regex_parser/in.i"
	@echo "... src/regex_parser/in.s"
	@echo "... src/regex_parser/max_repeat.o"
	@echo "... src/regex_parser/max_repeat.i"
	@echo "... src/regex_parser/max_repeat.s"
	@echo "... src/regex_parser/min_repeat.o"
	@echo "... src/regex_parser/min_repeat.i"
	@echo "... src/regex_parser/min_repeat.s"
	@echo "... src/regex_parser/opcode.o"
	@echo "... src/regex_parser/opcode.i"
	@echo "... src/regex_parser/opcode.s"
	@echo "... src/regex_parser/sre_parse.o"
	@echo "... src/regex_parser/sre_parse.i"
	@echo "... src/regex_parser/sre_parse.s"
	@echo "... src/regex_parser/state.o"
	@echo "... src/regex_parser/state.i"
	@echo "... src/regex_parser/state.s"
	@echo "... src/regex_parser/subpattern.o"
	@echo "... src/regex_parser/subpattern.i"
	@echo "... src/regex_parser/subpattern.s"
	@echo "... src/regex_parser/subpattern_opcode.o"
	@echo "... src/regex_parser/subpattern_opcode.i"
	@echo "... src/regex_parser/subpattern_opcode.s"
	@echo "... src/regex_parser/tokenizer.o"
	@echo "... src/regex_parser/tokenizer.i"
	@echo "... src/regex_parser/tokenizer.s"
	@echo "... src/schema.o"
	@echo "... src/schema.i"
	@echo "... src/schema.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

